CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role ENUM('admin', 'user') NOT NULL DEFAULT 'user',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  species VARCHAR(100),
  breed VARCHAR(100),
  birth_date DATE,
  gender ENUM('male', 'female', 'unknown') DEFAULT 'unknown',
  weight DECIMAL(6,2),
  color VARCHAR(100),
  microchip_id VARCHAR(100),
  photo_path VARCHAR(500),
  notes TEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vet_visits (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pet_id INT NOT NULL,
  visit_date DATETIME NOT NULL,
  is_future BOOLEAN DEFAULT FALSE,
  reason TEXT NOT NULL,
  diagnosis TEXT,
  treatment TEXT,
  vet_name VARCHAR(255),
  vet_clinic VARCHAR(255),
  notes TEXT,
  cost DECIMAL(10,2),
  reminder_enabled BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS medications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pet_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  dosage VARCHAR(100),
  unit VARCHAR(50),
  frequency VARCHAR(100),
  times_per_day INT,
  start_date DATE,
  end_date DATE,
  notes TEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS blood_work (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pet_id INT NOT NULL,
  exam_date DATE NOT NULL,
  description TEXT,
  file_path VARCHAR(500) NOT NULL,
  original_filename VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stool_entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pet_id INT NOT NULL,
  entry_date DATE NOT NULL,
  entry_time TIME,
  rating TINYINT NOT NULL,
  consistency VARCHAR(100),
  has_blood BOOLEAN DEFAULT FALSE,
  has_mucus BOOLEAN DEFAULT FALSE,
  notes TEXT,
  image_paths JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS behavior_entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pet_id INT NOT NULL,
  entry_date DATE NOT NULL,
  entry_time TIME,
  rating TINYINT NOT NULL,
  category VARCHAR(100),
  notes TEXT,
  image_paths JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS feeding_plans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pet_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS feeding_entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  feeding_plan_id INT NOT NULL,
  time_of_day TIME,
  food_type VARCHAR(255) NOT NULL,
  amount DECIMAL(8,2),
  unit VARCHAR(50),
  notes TEXT,
  FOREIGN KEY (feeding_plan_id) REFERENCES feeding_plans(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vaccinations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pet_id INT NOT NULL,
  vaccine_name VARCHAR(255) NOT NULL,
  vaccination_date DATE NOT NULL,
  next_due_date DATE,
  batch_number VARCHAR(100),
  vet_name VARCHAR(255),
  notes TEXT,
  reminder_enabled BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pet_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  event_date DATETIME NOT NULL,
  end_date DATETIME,
  description TEXT,
  category VARCHAR(100) DEFAULT 'misc',
  reminder_enabled BOOLEAN DEFAULT FALSE,
  reminder_at DATETIME,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reminders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  pet_id INT NOT NULL,
  ref_type ENUM('vet_visit', 'vaccination', 'event', 'medication') NOT NULL,
  ref_id INT NOT NULL,
  message TEXT NOT NULL,
  remind_at DATETIME NOT NULL,
  sent BOOLEAN DEFAULT FALSE,
  sent_at DATETIME,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS smtp_settings (
  id INT PRIMARY KEY DEFAULT 1,
  host VARCHAR(255),
  port INT DEFAULT 587,
  username VARCHAR(255),
  password_encrypted TEXT,
  from_email VARCHAR(255),
  from_name VARCHAR(255) DEFAULT 'Project Nemo',
  use_tls BOOLEAN DEFAULT TRUE,
  active BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plugins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  short_name VARCHAR(50) NOT NULL,
  long_name VARCHAR(255) NOT NULL,
  version VARCHAR(20),
  author VARCHAR(255),
  author_link VARCHAR(500),
  description TEXT,
  icon_path VARCHAR(500),
  active BOOLEAN DEFAULT TRUE,
  install_path VARCHAR(500),
  installed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT IGNORE INTO smtp_settings (id) VALUES (1);
